version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"            # your AWS region
    AWS_ACCOUNT_ID: "637423166046"     # your AWS account
    ECR_REPO: "my-rag-inference-repo"  # name of your ECR repository
    IMAGE_TAG: "v2"                    # image tag you want to push

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update
      - apt-get install -y docker.io
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t rag-inference:$IMAGE_TAG .
      - echo "Tagging image for ECR..."
      - docker tag rag-inference:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Build and push completed!"

