version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "637423166046"
    ECR_REPO: "my-rag-inference-repo"
    IMAGE_TAG: "v2"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y docker.io curl unzip
      - which aws && apt-get remove -y awscli || true
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install --update
      - aws --version

  pre_build:
    commands:
      - echo "Logging into OUR ECR repo for push..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - echo "Logging into Hugging Face DLC ECR (763104351884)..."
      - ECR_PASS=$(aws ecr get-login-password --region "$AWS_REGION" --registry-ids "763104351884")
      - docker login --username AWS --password-stdin "763104351884.dkr.ecr.$AWS_REGION.amazonaws.com" <<< "$ECR_PASS"

  build:
    commands:
      - docker build -f rag_deployment/Dockerfile -t rag-inference:"$IMAGE_TAG" rag_deployment/
      - docker tag rag-inference:"$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"

  post_build:
    commands:
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"
      - echo "Build and push completed!"

