version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "637423166046"
    ECR_REPO: "my-rag-inference-repo"
    IMAGE_TAG: "v4"

phases:
  install:
    commands:
      - echo "Installing Docker, Curl, and Unzip..."
      - apt-get update
      - apt-get install -y docker.io curl unzip

      - echo "Verifying new AWS CLI version..."
      - which aws
      - aws --version

  pre_build:
    commands:
      - echo "Logging into our ECR repo for push to $AWS_ACCOUNT_ID..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - echo "Logging into Hugging Face DLC ECR for base image pull (account 763104351884)..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "763104351884.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -f rag_deployment/Dockerfile -t "rag-inference:$IMAGE_TAG" rag_deployment/
      - echo "Tagging image for ECR..."
      - docker tag "rag-inference:$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"
      - echo "Build & push completed!"

