version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "637423166046"
    ECR_REPO: "my-rag-inference-repo"
    IMAGE_TAG: "v2"

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update
      - apt-get install -y docker.io
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      # 1) Use `-f` to point to your Dockerfile path:
      # 2) The final argument is the build context directory: `rag_deployment/`
      - docker build -f rag_deployment/Dockerfile -t rag-inference:$IMAGE_TAG rag_deployment/
      - echo "Tagging image for ECR..."
      - docker tag rag-inference:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Build and push completed!"

